markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Ohmbrewer.org
url: http://ohmbrewer.org
description: The web application for a happy brewday.
